
package documentservices.wms0.rbcfg.servicemessage;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.5
 * Fri Feb 13 14:18:49 IST 2015
 * Generated source version: 2.2.5
 * 
 */
 
public class WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessage_CustomBindingITwoWayAsync_Server{

    protected WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessage_CustomBindingITwoWayAsync_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessageImpl();
        String address = "http://10.211.38.145:8999/WS_CXF_Service/services";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new WMS0DSWebServiceBTOrcCoreProcessDocumentServicePortRcvSndDSMessage_CustomBindingITwoWayAsync_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
